### ISSUE TITLE
Crashlog mentioned #132 ( referenced by user seth72 ) using Duo2 

### ISSUE THREAD

**Issue by nunigaia** [betonme/e2openplugin-EnhancedMovieCenter#135]
Hi betonme,

Is it possible to fix this issue, regarding this crashlog content:

STB: Duo2
Image used: Blackhole 2.1.7.1 OE 2.0
EMC Version used from Ihad forum --> http://www.i-have-a-dreambox.com/wbb2/attachment.php?attachmentid=375411

Here is the crashlog details:

[code]

EMC: [sp] cleanupSetup exception:
cannot import name BT_SCALE
Unexpected error: <type 'exceptions.ImportError'>
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/EnhancedMovieCenter.py", line 157, in cleanupSetup
    from MovieSelection import purgeExpired
  File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieSelection.py", line 61, in <module>
    from MovieCenter import MovieCenter, getPlayerService, getProgress, detectBLUStructure, detectBLUISO
  File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieCenter.py", line 66, in <module>
    from enigma import BT_SCALE, BT_KEEP_ASPECT_RATIO
ImportError: cannot import name BT_SCALE

[/code]

Thanks 
nunigaia

hope you have a nice day

**Comment by nunigaia** [comment]
Thanks to Betonme
For now it´s working.

best regards
nunigaia
